### PR TITLE
Enable consumption of 'omit-parsing' flag to disable

### PR DESCRIPTION
**Pull request by arlandism**
This is a first pass #121.

Notably, it only handles the command-line invocation case. I was en route to tackling the other use-case but I can't understand the [identity check](https://github.com/slagyr/speclj/blob/master/src/clj/speclj/run/standard.clj#L51) in `standard.clj`. I tried running a single file to inspect the `active-runner` and `default-runner`. They were the same class but not the same instance. Given that, I'm not actually sure under what circumstances that check would return true. Any insight here would be much appreciated.

Uses:
`lein spec -p`
`lein spec --omit-pending`

### CODE REVIEW

**Comment by arlandism** [comment]
@trptcolin @slagyr Either of you have bandwidth to check this out?

**Comment by arlandism** [comment]
Bump

**Comment by slagyr** [comment]
Are these the same flags use in rspec?

**Comment by slagyr** [comment]
Check out [default-config](https://github.com/slagyr/speclj/blob/master/src/cljx/speclj/config.cljx#L42) and [with-config](https://github.com/slagyr/speclj/blob/master/src/cljx/speclj/config.cljx#L112).  A default setting for omit-pending should be added to the default and interpreted by with-config. 

The identity check will pass when you run an individual spec file, without the runner.

     java -cp `lein classpath` clojure.main spec/clj/speclj/running_spec.clj

Note the file has a (run-specs) at the bottom.  This call could include options:

    (run-specs :color true :omit-pending true)

Otherwise, commit looks good.  Thanks for the help and sorry for the delay.

**Comment by arlandism** [comment]
Thanks for the response, @slagyr. Working on this...

**Comment by arlandism** [comment]
@slagyr I think it's handled. FYI, here's how things look:

Original:

```
[arlandislawrence@charon-2:~/dev/projects/clojure/speclj on omit-pending]
% lein spec                                                                                                                                                                                           ✹ ✭
Rewriting src/cljx to target/src/clj (clj) with features #{clj} and 0 transformations.
Rewriting src/cljx to target/src/cljs (cljs) with features #{cljs} and 1 transformations.
Rewriting spec/cljx to target/spec/clj (clj) with features #{clj} and 0 transformations.
Rewriting spec/cljx to target/spec/cljs (cljs) with features #{cljs} and 1 transformations.
..................................*.................................................*............................................................................................................................................................................................

Pending:

  Running tracks one pass
    ; Not Yet Implemented
    ; /Users/arlandislawrence/dev/projects/clojure/speclj/spec/clj/speclj/running_spec.clj:23

Finished in 0.25557 seconds
271 examples, 0 failures, 1 pending
```

With feature:

```
[arlandislawrence@charon-2:~/dev/projects/clojure/speclj on omit-pending]
% lein spec -p                                                                                                                                                                                        ✹ ✭
Rewriting src/cljx to target/src/clj (clj) with features #{clj} and 0 transformations.
Rewriting src/cljx to target/src/cljs (cljs) with features #{cljs} and 1 transformations.
Rewriting spec/cljx to target/spec/clj (clj) with features #{clj} and 0 transformations.
Rewriting spec/cljx to target/spec/cljs (cljs) with features #{cljs} and 1 transformations.
..................................*.................................................*............................................................................................................................................................................................

Finished in 0.24588 seconds
271 examples, 0 failures, 1 pending
```

**Comment by slagyr** [comment]
Nice work.  Thanks for the contribution Arlandis?  This will be included in the next release 3.3.0.

**Pull request merged**
